import localFont from "next/font/local";
import "./globals.css";
import { ToasterContainer } from "./(components)/common/NotificationToaster";
import { cookies } from "next/headers";
import TopNavBar from "./(components)/common/TopNavBar";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata = {
    title: "Demo",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <TopNavBar />
                {children}
                <ToasterContainer />
            </body>
        </html>
    );
}
